/* eslint-disable no-unused-vars */
export enum City {
    Casablanca = 'Casablanca',
    Rabat = 'Rabat',
    Marrakech = 'Marrakech',
    Fes = 'Fes',
    Tanger = 'Tanger',
    Oujda = 'Oujda',
    Agadir = 'Agadir',
    Tetouan = 'Tetouan',
    Meknes = 'Meknes',
    Safi = 'Safi',
    ElJadida = 'El Jadida',
    Khouribga = 'Khouribga',
    Ouarzazate = 'Ouarzazate',
    Settat = 'Settat',
    SidiKacem = 'Sidi Kacem',
    Kenitra = 'Kenitra',
    Taza = 'Taza',
    Tiznit = 'Tiznit',
    SidiIfni = 'Sidi Ifni',
}